### Consulta 1: Obtener un dato aleatorio sobre gatos (GET)
GET https://meowfacts.herokuapp.com/ HTTP/1.1


### Consulta 2: Obtener información de Pokémon (GET)
GET https://pokeapi.co/api/v2/pokemon/pikachu HTTP/1.1


### Consulta 3: Obtener un chiste aleatorio de Chuck Norris (GET)
GET https://api.chucknorris.io/jokes/random HTTP/1.1


### Consulta 4: Obtener una receta aleatoria (GET)
GET https://www.themealdb.com/api/json/v1/1/random.php HTTP/1.1

### Consulta 5: Buscar imágenes de perros aleatorios (GET)
GET https://dog.ceo/api/breeds/image/random HTTP/1.1

### Consulta 6: Generar una imagen de un gatito (GET)
GET https://cataas.com/cat?json=true HTTP/1.1

### Consulta 7: Crear un usuario en un sistema de autenticación (POST)
POST https://dummyjson.com/users/add HTTP/1.1
Content-Type: application/json

{
  "firstName": "David",
  "lastName": "Pérez",
  "age": 25,
  "gender": "Male",
  "email": "David.perez@example.com"
}

### Consulta 8: Crear un producto de prueba (POST)
POST https://dummyjson.com/products/add HTTP/1.1
Content-Type: application/json

{
  "title": "Laptop Gamer",
  "description": "Laptop Gaming Acer Nitro V",
  "price": 1500,
  "stock": 10
}

### Consulta 9: Crear una tarea (POST)
POST https://dummyjson.com/todos/add HTTP/1.1
Content-Type: application/json

{
  "todo": "Terminar proyecto API",
  "completed": false,
  "userId": 5
}

### Consulta 10: Crear una mascota en un sistema de gestión de mascotas (POST)
POST https://petstore.swagger.io/v2/pet HTTP/1.1
Content-Type: application/json

{
  "id": 12345,
  "name": "Firulais",
  "category": {
    "id": 1,
    "name": "Perro"
  },
  "status": "available"
}

### Consulta 11: Actualizar un usuario (PUT)
PUT https://dummyjson.com/users/1 HTTP/1.1
Content-Type: application/json

{
  "firstName": "Carlos",
  "lastName": "Ramírez",
  "age": 30,
  "gender": "Male",
  "email": "carlos.ramirez@example.com"
}

### Consulta 12: Eliminar un usuario (DELETE)
DELETE https://dummyjson.com/users/1 HTTP/1.1

### ruta backup C:\Users\ACER\AppData\Roaming\Code\User\globalStorage\anweber.vscode-httpyac\.httpyac 