/**
 * API Empleados
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiEmpleados);
  }
}(this, function(expect, ApiEmpleados) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiEmpleados.Empleado();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Empleado', function() {
    it('should create an instance of Empleado', function() {
      // uncomment below and update the code to test Empleado
      //var instance = new ApiEmpleados.Empleado();
      //expect(instance).to.be.a(ApiEmpleados.Empleado);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new ApiEmpleados.Empleado();
      //expect(instance).to.be();
    });

    it('should have the property nombre (base name: "nombre")', function() {
      // uncomment below and update the code to test the property nombre
      //var instance = new ApiEmpleados.Empleado();
      //expect(instance).to.be();
    });

    it('should have the property edad (base name: "edad")', function() {
      // uncomment below and update the code to test the property edad
      //var instance = new ApiEmpleados.Empleado();
      //expect(instance).to.be();
    });

    it('should have the property pais (base name: "pais")', function() {
      // uncomment below and update the code to test the property pais
      //var instance = new ApiEmpleados.Empleado();
      //expect(instance).to.be();
    });

    it('should have the property cargo (base name: "cargo")', function() {
      // uncomment below and update the code to test the property cargo
      //var instance = new ApiEmpleados.Empleado();
      //expect(instance).to.be();
    });

    it('should have the property anios (base name: "anios")', function() {
      // uncomment below and update the code to test the property anios
      //var instance = new ApiEmpleados.Empleado();
      //expect(instance).to.be();
    });

  });

}));
