/**
 * API Empleados
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiEmpleados);
  }
}(this, function(expect, ApiEmpleados) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiEmpleados.EmpleadosApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EmpleadosApi', function() {
    describe('empleadosDelete', function() {
      it('should call empleadosDelete successfully', function(done) {
        //uncomment below and update the code to test empleadosDelete
        //instance.empleadosDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('empleadosGet', function() {
      it('should call empleadosGet successfully', function(done) {
        //uncomment below and update the code to test empleadosGet
        //instance.empleadosGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('empleadosPost', function() {
      it('should call empleadosPost successfully', function(done) {
        //uncomment below and update the code to test empleadosPost
        //instance.empleadosPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('empleadosPut', function() {
      it('should call empleadosPut successfully', function(done) {
        //uncomment below and update the code to test empleadosPut
        //instance.empleadosPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
