/**
 * API Empleados
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EmpleadoInput model module.
 * @module model/EmpleadoInput
 * @version 1.0.0
 */
class EmpleadoInput {
    /**
     * Constructs a new <code>EmpleadoInput</code>.
     * @alias module:model/EmpleadoInput
     * @param nombre {String} 
     * @param edad {Number} 
     * @param pais {String} 
     * @param cargo {String} 
     * @param anios {Number} 
     */
    constructor(nombre, edad, pais, cargo, anios) { 
        
        EmpleadoInput.initialize(this, nombre, edad, pais, cargo, anios);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, nombre, edad, pais, cargo, anios) { 
        obj['nombre'] = nombre;
        obj['edad'] = edad;
        obj['pais'] = pais;
        obj['cargo'] = cargo;
        obj['anios'] = anios;
    }

    /**
     * Constructs a <code>EmpleadoInput</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmpleadoInput} obj Optional instance to populate.
     * @return {module:model/EmpleadoInput} The populated <code>EmpleadoInput</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmpleadoInput();

            if (data.hasOwnProperty('nombre')) {
                obj['nombre'] = ApiClient.convertToType(data['nombre'], 'String');
            }
            if (data.hasOwnProperty('edad')) {
                obj['edad'] = ApiClient.convertToType(data['edad'], 'Number');
            }
            if (data.hasOwnProperty('pais')) {
                obj['pais'] = ApiClient.convertToType(data['pais'], 'String');
            }
            if (data.hasOwnProperty('cargo')) {
                obj['cargo'] = ApiClient.convertToType(data['cargo'], 'String');
            }
            if (data.hasOwnProperty('anios')) {
                obj['anios'] = ApiClient.convertToType(data['anios'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EmpleadoInput</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EmpleadoInput</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EmpleadoInput.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['nombre'] && !(typeof data['nombre'] === 'string' || data['nombre'] instanceof String)) {
            throw new Error("Expected the field `nombre` to be a primitive type in the JSON string but got " + data['nombre']);
        }
        // ensure the json data is a string
        if (data['pais'] && !(typeof data['pais'] === 'string' || data['pais'] instanceof String)) {
            throw new Error("Expected the field `pais` to be a primitive type in the JSON string but got " + data['pais']);
        }
        // ensure the json data is a string
        if (data['cargo'] && !(typeof data['cargo'] === 'string' || data['cargo'] instanceof String)) {
            throw new Error("Expected the field `cargo` to be a primitive type in the JSON string but got " + data['cargo']);
        }

        return true;
    }


}

EmpleadoInput.RequiredProperties = ["nombre", "edad", "pais", "cargo", "anios"];

/**
 * @member {String} nombre
 */
EmpleadoInput.prototype['nombre'] = undefined;

/**
 * @member {Number} edad
 */
EmpleadoInput.prototype['edad'] = undefined;

/**
 * @member {String} pais
 */
EmpleadoInput.prototype['pais'] = undefined;

/**
 * @member {String} cargo
 */
EmpleadoInput.prototype['cargo'] = undefined;

/**
 * @member {Number} anios
 */
EmpleadoInput.prototype['anios'] = undefined;






export default EmpleadoInput;

