/**
 * API Empleados
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EmpleadoDelete model module.
 * @module model/EmpleadoDelete
 * @version 1.0.0
 */
class EmpleadoDelete {
    /**
     * Constructs a new <code>EmpleadoDelete</code>.
     * @alias module:model/EmpleadoDelete
     * @param id {Number} 
     */
    constructor(id) { 
        
        EmpleadoDelete.initialize(this, id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id) { 
        obj['id'] = id;
    }

    /**
     * Constructs a <code>EmpleadoDelete</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmpleadoDelete} obj Optional instance to populate.
     * @return {module:model/EmpleadoDelete} The populated <code>EmpleadoDelete</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmpleadoDelete();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EmpleadoDelete</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EmpleadoDelete</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EmpleadoDelete.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

EmpleadoDelete.RequiredProperties = ["id"];

/**
 * @member {Number} id
 */
EmpleadoDelete.prototype['id'] = undefined;






export default EmpleadoDelete;

